### ISSUE TITLE
Support for wayland 

### ISSUE THREAD

**Issue by verterok** [jetho/Hclip#7]
Hi, I'm an indirect user of the library (matterhorn user)
Would be possible to get support wayland clipboard: wl-copy and wl-paste, alongside xsel/xclip?
I'm currently using a hack-ish workaround by using a custom script impersonating xclip but calling wl-copy/wl-paste under the hood

Thanks

**Comment by mfourne** [comment]
Not having seen #8 before, I implemented basically the same (but with wl-paste --no-newline). Since we already have this one, I felt no need to open another PR.
